FROM node:16.14.0

ARG NODE_ENV
ARG DATABASE
ARG USERNAME
ARG PASSWORD
ARG PORT
ARG HOST
ARG JWT_SECRET_KEY
ARG JWT_EXPIRE_IN
ARG CLOUD_NAME
ARG API_KEY
ARG API_SECRET
ARG API_VARIABLE

ENV NODE_ENV=$NODE_ENV
ENV DATABASE=$DATABASE
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD
ENV PORT=$PORT
ENV HOST=$HOST
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY
ENV JWT_EXPIRE_IN=$JWT_EXPIRE_IN
ENV CLOUD_NAME=$CLOUD_NAME
ENV API_KEY=$API_KEY
ENV API_SECRET=$API_SECRET
ENV API_VARIABLE=$API_VARIABLE

WORKDIR /usr/src/app
COPY package*.json ./
RUN yarn install
COPY . .
RUN yarn build

EXPOSE ${PORT}
CMD [ "yarn", "start" ]